jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    
    # ADICIONE ESTAS DUAS LINHAS AQUI
    permissions:
      contents: write

    steps:
      - name: '1. Checkout do repositório'
        uses: actions/checkout@v4

      - name: '2. Configurar Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: '3. Instalar dependências'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: '4. Executar script de atualização'
        run: python scripts/carrega_dados_vpa.py

      - name: '5. Commit e Push das alterações (se houver)'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff --staged --quiet; then
            echo "Nenhuma alteração para commitar."
          else
            git commit -m "📊 Atualização automática dos dados"
            git push
          fi
